export const algorithmData = [
  {
    name: 'Logistic Regression',
    type: 'classification',
    whenToUse: 'Binary classification problems where you need probabilities and linear decision boundaries.',
    advantages: ['Fast training', 'Highly interpretable', 'Provides probabilities'],
    disadvantages: ['Assumes linear relationship', 'Prone to underfitting complex data', 'Struggles with non-linear boundaries'],
    timeComplexity: 'O(n * d)',
    spaceComplexity: 'O(d)',
    assumptions: ['Linearity of independent variables and log odds', 'Absence of multicollinearity'],
    overfittingTendency: 'Low',
    biasVariance: 'High bias, low variance',
    realWorldApps: ['Spam detection', 'Credit scoring', 'Disease prediction']
  },
  {
    name: 'Decision Tree',
    type: 'both',
    whenToUse: 'When interpretability is critical and data has non-linear relationships or mixed feature types.',
    advantages: ['Easy to interpret (if shallow)', 'Handles non-linear data', 'No feature scaling required', 'Handles missing values well'],
    disadvantages: ['Highly prone to overfitting', 'Unstable (small data changes cause large tree changes)', 'Greedy algorithm may not find global optimum'],
    timeComplexity: 'O(n * d * log(n))',
    spaceComplexity: 'O(nodes)',
    assumptions: ['No strong assumptions about data distribution'],
    overfittingTendency: 'Very High',
    biasVariance: 'Low bias, high variance',
    realWorldApps: ['Customer segmentation', 'Medical diagnosis rules', 'Loan approval']
  },
  {
    name: 'Random Forest',
    type: 'both',
    whenToUse: 'Medium to large datasets with complex non-linear relationships where high accuracy is needed.',
    advantages: ['Handles non-linear data', 'Resistant to overfitting', 'Provides feature importance', 'Handles missing values'],
    disadvantages: ['Slower training and prediction', 'Less interpretable than a single tree', 'Large memory footprint'],
    timeComplexity: 'O(n * d * k * log(n))',
    spaceComplexity: 'O(k * nodes)',
    assumptions: ['No strong assumptions about data distribution'],
    overfittingTendency: 'Low',
    biasVariance: 'Low bias, moderate variance (controlled by ensemble)',
    realWorldApps: ['Fraud detection', 'Medical diagnosis', 'Stock market prediction']
  },
  {
    name: 'SVM',
    type: 'classification',
    whenToUse: 'High-dimensional spaces or when the number of dimensions exceeds the number of samples.',
    advantages: ['Effective in high-dimensional spaces', 'Memory efficient (uses support vectors)', 'Versatile via kernel trick'],
    disadvantages: ['Poor performance on large datasets (slow training)', 'Sensitive to noisy data/outliers', 'Choosing the right kernel can be tricky'],
    timeComplexity: 'O(n^2) to O(n^3)',
    spaceComplexity: 'O(n * d)',
    assumptions: ['Data is linearly separable (in original or kernel space)'],
    overfittingTendency: 'Moderate (depends on C and kernel)',
    biasVariance: 'Moderate bias, moderate variance',
    realWorldApps: ['Image classification', 'Bioinformatics (e.g., cancer classification)', 'Text categorization']
  },
  {
    name: 'KNN',
    type: 'both',
    whenToUse: 'Small datasets where decision boundaries are highly irregular.',
    advantages: ['Simple to understand and implement', 'No training phase (lazy learning)', 'Naturally handles multi-class'],
    disadvantages: ['Very slow prediction on large datasets', 'Sensitive to irrelevant features', 'Requires feature scaling', 'High memory usage'],
    timeComplexity: 'O(1) training, O(n * d) prediction',
    spaceComplexity: 'O(n * d)',
    assumptions: ['Similar inputs have similar outputs', 'All features are equally important (unless weighted)'],
    overfittingTendency: 'High (for small k)',
    biasVariance: 'Low bias, high variance (for small k)',
    realWorldApps: ['Recommendation systems', 'Image recognition', 'Pattern recognition']
  },
  {
    name: 'Naive Bayes',
    type: 'classification',
    whenToUse: 'Text classification or when you have many features but limited training data.',
    advantages: ['Extremely fast training and prediction', 'Works well with high-dimensional data', 'Performs well even if independence assumption is violated'],
    disadvantages: ['Assumes features are conditionally independent', 'Poor probability estimator (outputs are often pushed to 0 or 1)', 'Zero frequency problem (requires smoothing)'],
    timeComplexity: 'O(n * d)',
    spaceComplexity: 'O(c * d)',
    assumptions: ['Features are conditionally independent given the class'],
    overfittingTendency: 'Low',
    biasVariance: 'High bias, low variance',
    realWorldApps: ['Spam filtering', 'Sentiment analysis', 'Document categorization']
  },
  {
    name: 'XGBoost',
    type: 'both',
    whenToUse: 'Winning Kaggle competitions, tabular data where highest performance is required.',
    advantages: ['Often achieves state-of-the-art results', 'Built-in regularization to prevent overfitting', 'Handles missing values automatically', 'Parallel processing'],
    disadvantages: ['Can be prone to overfitting if not tuned carefully', 'Many hyperparameters to tune', 'Slower training than Random Forest (sequential tree building)'],
    timeComplexity: 'O(k * d * x)',
    spaceComplexity: 'O(k * nodes)',
    assumptions: ['No strong assumptions'],
    overfittingTendency: 'Moderate to High (requires tuning)',
    biasVariance: 'Low bias, moderate variance',
    realWorldApps: ['Click-through rate prediction', 'Ranking problems', 'Complex tabular data tasks']
  },
  {
    name: 'Linear Regression',
    type: 'regression',
    whenToUse: 'Predicting a continuous value when there is a linear relationship between features and target.',
    advantages: ['Fast training', 'Highly interpretable', 'Simple to implement'],
    disadvantages: ['Assumes linear relationship', 'Sensitive to outliers', 'Prone to underfitting complex data'],
    timeComplexity: 'O(n * d^2 + d^3)',
    spaceComplexity: 'O(d)',
    assumptions: ['Linearity', 'Homoscedasticity', 'Independence of errors', 'Normality of error distribution'],
    overfittingTendency: 'Low',
    biasVariance: 'High bias, low variance',
    realWorldApps: ['House price prediction', 'Sales forecasting', 'Economic modeling']
  },
  {
    name: 'Ridge Regression',
    type: 'regression',
    whenToUse: 'Linear regression problems where multicollinearity exists among features.',
    advantages: ['Reduces model complexity', 'Prevents overfitting', 'Handles multicollinearity better than plain Linear Regression'],
    disadvantages: ['Includes all features in the final model (no feature selection)', 'Assumes linear relationship'],
    timeComplexity: 'O(n * d^2 + d^3)',
    spaceComplexity: 'O(d)',
    assumptions: ['Linearity', 'Homoscedasticity', 'Independence of errors'],
    overfittingTendency: 'Low',
    biasVariance: 'Moderate bias, low variance',
    realWorldApps: ['Any regression task with highly correlated features']
  },
  {
    name: 'Lasso Regression',
    type: 'regression',
    whenToUse: 'Linear regression problems where you want built-in feature selection.',
    advantages: ['Performs feature selection by shrinking some coefficients to zero', 'Prevents overfitting', 'Produces simpler and more interpretable models'],
    disadvantages: ['Can arbitrarily select one feature from a group of highly correlated features', 'Struggles if number of features > number of samples'],
    timeComplexity: 'O(n * d^2)',
    spaceComplexity: 'O(d)',
    assumptions: ['Linearity', 'Homoscedasticity', 'Independence of errors'],
    overfittingTendency: 'Low',
    biasVariance: 'Moderate bias, low variance',
    realWorldApps: ['High-dimensional datasets needing feature selection (e.g., genomics)']
  },
  {
    name: 'SVR',
    type: 'regression',
    whenToUse: 'Regression tasks in high-dimensional spaces with non-linear relationships.',
    advantages: ['Robust to outliers (epsilon-insensitive tube)', 'Effective in high-dimensional spaces', 'Versatile via kernel trick'],
    disadvantages: ['Poor scaling with large datasets', 'Difficult to interpret', 'Requires careful tuning of C, epsilon, and kernel parameters'],
    timeComplexity: 'O(n^2) to O(n^3)',
    spaceComplexity: 'O(n * d)',
    assumptions: ['Data relationship can be captured within the epsilon tube (in kernel space)'],
    overfittingTendency: 'Moderate (depends on parameters)',
    biasVariance: 'Moderate bias, moderate variance',
    realWorldApps: ['Time series prediction', 'Financial forecasting']
  }
];
