/**
 * Evolution Simulator Engine — Step-by-step interactive evolutionary trajectory walkthroughs
 */

export const EVOLUTION_TRAJECTORIES = [
  {
    id: 'tree-lineage',
    title: 'The Great Tree Evolution: From Single Branch to Gradient Boosting',
    description: 'Watch how decision trees evolved from high-variance simple split rules into state-of-the-art XGBoost & LightGBM gradient ensembles.',
    steps: [
      {
        step: 1,
        modelId: 'decision-tree',
        title: 'Gen-2: The Single Decision Tree (1984)',
        mutationSummary: 'Introduced axis-aligned greedy recursive split rules.',
        whyEvolved: 'Replaced manual rule programming with data-driven decision trees. However, deep trees suffered from extreme variance & overfitting.',
        keyMutation: 'Axis-Aligned Splitting',
        traitDelta: { bias: '-40%', variance: '+60%' },
      },
      {
        step: 2,
        modelId: 'random-forest',
        title: 'Gen-3: Random Forest Bagging (2001)',
        mutationSummary: 'Added Bootstrap Aggregating & Random Feature Subsampling.',
        whyEvolved: 'Averaging 100 decorrelated trees drastically reduced variance without increasing bias, solving single tree overfitting.',
        keyMutation: 'Feature Subsampling + Bagging',
        traitDelta: { variance: '-65%', generalization: '+38%' },
      },
      {
        step: 3,
        modelId: 'gradient-boosting',
        title: 'Gen-3: Gradient Boosting (1999)',
        mutationSummary: 'Sequential residual fitting in function space.',
        whyEvolved: 'Instead of random trees voting independently, sequential trees fit the loss gradient residuals of previous trees.',
        keyMutation: 'Residual Fitting Gradient Descent',
        traitDelta: { bias: '-10%', generalization: '+4%' },
      },
      {
        step: 4,
        modelId: 'xgboost',
        title: 'Gen-4: XGBoost (2014)',
        mutationSummary: 'Second-order Taylor expansion + L1/L2 leaf regularization.',
        whyEvolved: 'Added 2nd-order Taylor series curvature optimization and cache-aware histogram split searching for industrial speed & accuracy.',
        keyMutation: '2nd-Order Taylor Regularization',
        traitDelta: { speed: '+20%', trainingStability: '+10%' },
      },
      {
        step: 5,
        modelId: 'lightgbm',
        title: 'Gen-4: LightGBM (2017)',
        mutationSummary: 'GOSS (One-Side Sampling) & EFB (Exclusive Feature Bundling).',
        whyEvolved: 'Prioritizing high-gradient samples (GOSS) speeds up training 10x on multi-million row datasets.',
        keyMutation: 'GOSS + EFB Bundling',
        traitDelta: { speed: '+30%', memoryEfficiency: '+15%' },
      },
    ],
  },
  {
    id: 'deep-learning-lineage',
    title: 'The Neural Explosion: From Single Neuron to ResNet',
    description: 'Trace the mutation from Rosenblatt Perceptron to 152-layer Deep Residual Networks.',
    steps: [
      {
        step: 1,
        modelId: 'perceptron',
        title: 'Gen-1: Rosenblatt Perceptron (1958)',
        mutationSummary: 'First single-neuron linear threshold unit.',
        whyEvolved: 'Proved machines could learn weights automatically. However, failed on non-linear XOR splits.',
        keyMutation: 'Linear Threshold Unit',
        traitDelta: { bias: '90%', interpretability: '90%' },
      },
      {
        step: 2,
        modelId: 'mlp',
        title: 'Gen-2: Multi-Layer Perceptron (1986)',
        mutationSummary: 'Backpropagation + Non-linear Activation Layers.',
        whyEvolved: 'Backprop enabled multi-layer deep learning, solving the XOR crisis and learning complex non-linear boundaries.',
        keyMutation: 'Backpropagation Gradient Chain Rule',
        traitDelta: { bias: '-75%', generalization: '+25%' },
      },
      {
        step: 3,
        modelId: 'cnn',
        title: 'Gen-3: Convolutional Neural Network (2012)',
        mutationSummary: '2D Spatial Filter Weight Sharing + Max Pooling.',
        whyEvolved: 'Translational invariant 2D convolution reduced parameters by 99% compared to dense MLPs for computer vision.',
        keyMutation: 'Translational Weight Sharing',
        traitDelta: { generalization: '+9%', featureEngineeringDependency: '-25%' },
      },
      {
        step: 4,
        modelId: 'resnet',
        title: 'Gen-4: Residual Network (2015)',
        mutationSummary: 'Identity Skip Connections F(x) + x.',
        whyEvolved: 'Skip connections created smooth gradient highways, allowing networks to scale from 20 layers to 152+ layers without vanishing gradients.',
        keyMutation: 'Identity Residual Shortcuts',
        traitDelta: { trainingStability: '+11%', generalization: '+3%' },
      },
    ],
  },
  {
    id: 'llm-lineage',
    title: 'The Language Revolution: From Recurrence to GPT-4',
    description: 'Explore how NLP evolved from step-by-step recurrent loops to massive parallel Transformer Attention.',
    steps: [
      {
        step: 1,
        modelId: 'lstm',
        title: 'Gen-3: LSTM Gated Recurrence (1997)',
        mutationSummary: 'Gated cell state accumulation (Forget, Input, Output).',
        whyEvolved: 'Solved classic RNN vanishing gradients by preserving long-term temporal cell memory across sequence steps.',
        keyMutation: 'Gated Cell Memory State',
        traitDelta: { noiseTolerance: '+82%', speed: '55%' },
      },
      {
        step: 2,
        modelId: 'transformer',
        title: 'Gen-5: Transformer Self-Attention (2017)',
        mutationSummary: 'Multi-Head Self-Attention QKᵀ / √d_k without Recurrence.',
        whyEvolved: 'Replaced sequential loops with parallel self-attention, allowing full GPU parallelization and O(1) pairwise token paths.',
        keyMutation: 'Multi-Head Self-Attention',
        traitDelta: { parallelization: '+74%', speed: '+35%' },
      },
      {
        step: 3,
        modelId: 'gpt',
        title: 'Gen-6: Autoregressive Decoder LLM (2018-2026)',
        mutationSummary: 'Causal Masked Next-Token Prediction at Trillion Parameter Scale.',
        whyEvolved: 'Scaling decoder-only transformers with self-supervised pre-training unlocked emergent reasoning, code, and zero-shot problem solving.',
        keyMutation: 'Emergent In-Context Scaling',
        traitDelta: { generalization: '+99%', interpretability: '15%' },
      },
    ],
  },
]
