/**
 * Model Genome Database — The Complete DNA Catalog of Machine Learning Algorithms
 * Contains 30+ species across Classical ML, Ensembles, Neural Networks, Attention/LLMs, & Unsupervised Learning.
 */

export const GENOME_DATABASE = [
  // --- CLASSICAL STATISTICAL LINEAGE ---
  {
    id: 'linear-regression',
    name: 'Linear Regression',
    speciesCode: 'SP-LR-001',
    family: 'Linear Models',
    generation: 'Gen-1 (1805 Gauss / Legendre)',
    algorithmType: 'Parametric Regression',
    architecture: 'Single Hyperplane wᵀx + b',
    learningParadigm: 'Supervised Learning',
    inputType: 'Continuous Tabular Features',
    outputType: 'Continuous Scalar y ∈ ℝ',
    parameters: 'w ∈ ℝᵈ, b ∈ ℝ (d + 1 parameters)',
    hyperparameters: {
      fitIntercept: true,
      regularization: 'None (OLS)',
      alpha: 0.0,
      solver: 'Closed-Form (Normal Equation / SVD)',
    },
    trainingStyle: 'Ordinary Least Squares (OLS) / Closed-Form Matrix Inversion',
    optimizationStrategy: 'Minimizing Residual Sum of Squares (RSS) J(w) = 1/2n ||y - Xw||²',
    decisionMechanism: 'Linear combination of weighted input features',
    complexity: {
      trainTime: 'O(n · d² + d³)',
      inferTime: 'O(d)',
      memory: 'O(d)',
      scalability: 'High for small d; requires SGD for huge datasets',
    },
    traits: {
      bias: 85, // High bias (simple linear assumption)
      variance: 15, // Low variance
      generalization: 75,
      interpretability: 98,
      speed: 98,
      memoryEfficiency: 95,
      parallelization: 80,
      featureEngineeringDependency: 90,
      noiseTolerance: 40,
      trainingStability: 99,
    },
    ancestors: [],
    descendants: ['logistic-regression', 'ridge-lasso', 'perceptron'],
    ecosystem: 'Regression & Tabular Analytics',
    strengths: [
      'Extremely fast closed-form solution and real-time inference',
      '100% interpretable feature coefficients (w_i represents marginal effect)',
      'Guaranteed global minimum (convex quadratic loss landscape)',
    ],
    weaknesses: [
      'Cannot model non-linear relationships without manual feature expansion',
      'Highly sensitive to multicollinearity and extreme outliers',
      'Assumes homoscedasticity and Gaussian error distribution',
    ],
    failureConditions: [
      'Rank-deficient feature matrix (Multicollinearity / rank(X) < d)',
      'Severe non-linear target distributions without polynomial kernels',
    ],
    historicalMilestones: {
      year: 1805,
      creator: 'Carl Friedrich Gauss & Adrien-Marie Legendre',
      breakthrough: 'First mathematical formulation of least squares data fitting',
    },
  },

  {
    id: 'logistic-regression',
    name: 'Logistic Regression',
    speciesCode: 'SP-LR-002',
    family: 'Linear Models',
    generation: 'Gen-1 (1958 David Cox)',
    algorithmType: 'Generalized Linear Model (GLM)',
    architecture: 'Sigmoidal Linear Boundary σ(wᵀx + b)',
    learningParadigm: 'Supervised Learning',
    inputType: 'Continuous & Categorical Features',
    outputType: 'Probability P(Y=1|X) ∈ [0, 1]',
    parameters: 'w ∈ ℝᵈ, b ∈ ℝ',
    hyperparameters: {
      penalty: 'L2 (Ridge) / L1 (Lasso)',
      C: 1.0,
      solver: 'L-BFGS / Coordinate Descent',
      maxIter: 100,
    },
    trainingStyle: 'Maximum Likelihood Estimation (MLE)',
    optimizationStrategy: 'Binary Cross-Entropy Loss J(w) = -1/n ∑ [y log(ŷ) + (1-y) log(1-ŷ)] via Gradient Descent',
    decisionMechanism: 'Sigmoidal mapping of linear hyperplane log-odds ratio',
    complexity: {
      trainTime: 'O(n · d · iterations)',
      inferTime: 'O(d)',
      memory: 'O(d)',
      scalability: 'Excellent for high-dimensional sparse text vectors',
    },
    traits: {
      bias: 75,
      variance: 25,
      generalization: 80,
      interpretability: 95,
      speed: 95,
      memoryEfficiency: 95,
      parallelization: 85,
      featureEngineeringDependency: 85,
      noiseTolerance: 50,
      trainingStability: 98,
    },
    ancestors: ['linear-regression'],
    descendants: ['perceptron', 'softmax-regression', 'svm'],
    ecosystem: 'Binary Classification & Risk Scoring',
    strengths: [
      'Outputs well-calibrated posterior probabilities, not just discrete class labels',
      'Efficient L1 regularization produces sparse feature selection',
      'Convex optimization landscape guarantees convergence without local minima',
    ],
    weaknesses: [
      'Linear decision boundary cannot separate non-linearly separable data',
      'Requires feature scaling and normalization for gradient stability',
      'Prone to underfitting on complex high-order interaction data',
    ],
    failureConditions: [
      'Perfect linear separation causing coefficient explosion (without L2 penalty)',
      'Severe class imbalance without class-weight rebalancing',
    ],
    historicalMilestones: {
      year: 1958,
      creator: 'David Cox',
      breakthrough: 'Introduced logistic log-odds mapping for binary probabilities',
    },
  },

  // --- DECISION TREES & ENSEMBLE LINEAGE ---
  {
    id: 'decision-tree',
    name: 'Decision Tree (CART / C4.5)',
    speciesCode: 'SP-DT-010',
    family: 'Tree-Based Species',
    generation: 'Gen-2 (1984 Leo Breiman)',
    algorithmType: 'Non-Parametric Axis-Aligned Partitioning',
    architecture: 'Hierarchical Binary Split Tree Structure',
    learningParadigm: 'Supervised Learning',
    inputType: 'Tabular (Continuous & Categorical)',
    outputType: 'Class Label or Continuous Prediction',
    parameters: 'Nodes, Split Thresholds, Node Values',
    hyperparameters: {
      maxDepth: 6,
      minSamplesSplit: 2,
      minSamplesLeaf: 1,
      criterion: 'Gini Impurity / Entropy / MSE',
    },
    trainingStyle: 'Recursive Greedy Binary Splitting',
    optimizationStrategy: 'Maximize Information Gain ΔI = Impurity(Parent) - ∑ [N_child/N_parent · Impurity(Child)]',
    decisionMechanism: 'Axis-aligned recursive hyper-rectangle partition rules',
    complexity: {
      trainTime: 'O(n · d · log n)',
      inferTime: 'O(depth)',
      memory: 'O(nodes)',
      scalability: 'Fast training; prone to memory explosion on unpruned deep trees',
    },
    traits: {
      bias: 15, // Low bias
      variance: 90, // High variance
      generalization: 50,
      interpretability: 96,
      speed: 92,
      memoryEfficiency: 85,
      parallelization: 30,
      featureEngineeringDependency: 20, // Requires minimal preprocessing!
      noiseTolerance: 35,
      trainingStability: 40, // Small data change changes entire tree
    },
    ancestors: ['linear-regression'],
    descendants: ['random-forest', 'gradient-boosting'],
    ecosystem: 'Tabular Analytics & Rule Engines',
    strengths: [
      'Requires zero feature scaling, normalization, or dummy encoding',
      '100% white-box rule tree visualization readable by domain experts',
      'Handles mixed continuous and categorical data effortlessly',
    ],
    weaknesses: [
      'Extremely high variance — small data fluctuations alter the entire tree',
      'Step-wise axis-aligned boundaries approximate smooth diagonal curves poorly',
      'Highly prone to severe overfitting if depth is unconstrained',
    ],
    failureConditions: [
      'Unconstrained depth on noisy datasets causing memorization of noise',
      'Smooth rotational patterns (e.g., XOR diagonal splits)',
    ],
    historicalMilestones: {
      year: 1984,
      creator: 'Leo Breiman, Jerome Friedman, Richard Olshen, Charles Stone',
      breakthrough: 'Introduced Classification and Regression Trees (CART)',
    },
  },

  {
    id: 'random-forest',
    name: 'Random Forest',
    speciesCode: 'SP-RF-011',
    family: 'Tree-Based Species',
    generation: 'Gen-3 (2001 Leo Breiman)',
    algorithmType: 'Ensemble Bagging (Bootstrap Aggregating)',
    architecture: 'Forest of Independent Decision Trees with Feature Subsampling',
    learningParadigm: 'Supervised Learning',
    inputType: 'Tabular (Mixed Numerical & Categorical)',
    outputType: 'Majority Vote / Average Prediction',
    parameters: 'Collection of N_trees Decision Trees',
    hyperparameters: {
      nEstimators: 100,
      maxDepth: 12,
      maxFeatures: 'sqrt(d)',
      bootstrap: true,
      criterion: 'Gini / Entropy',
    },
    trainingStyle: 'Parallel Independent Tree Induction on Bootstrap Samples',
    optimizationStrategy: 'Variance Reduction via Aggregation Var(X̄) = σ²/N + ρ·σ²(1 - 1/N)',
    decisionMechanism: 'Unweighted probabilistic voting across decorrelated decision trees',
    complexity: {
      trainTime: 'O(N_trees · n · d_sub · log n)',
      inferTime: 'O(N_trees · depth)',
      memory: 'O(N_trees · nodes)',
      scalability: 'Embarrassingly parallelizable across CPU cores',
    },
    traits: {
      bias: 25,
      variance: 25, // Drastically lower variance than single tree!
      generalization: 88,
      interpretability: 60,
      speed: 85,
      memoryEfficiency: 70,
      parallelization: 98, // Multi-core CPU parallel
      featureEngineeringDependency: 20,
      noiseTolerance: 82,
      trainingStability: 92,
    },
    ancestors: ['decision-tree'],
    descendants: ['extra-trees', 'gradient-boosting'],
    ecosystem: 'General Purpose Tabular ML',
    strengths: [
      'Drastically reduces variance without increasing bias',
      'Provides Out-Of-Bag (OOB) error estimation without separate validation set',
      'Computes robust feature importance rankings via mean Gini decrease',
    ],
    weaknesses: [
      'Cannot extrapolate predictions beyond the training feature range',
      'Large tree count increases memory footprint and inference latency',
      'Less interpretable than a single decision tree',
    ],
    failureConditions: [
      'Extremely high-dimensional sparse text vectors (where SVM/Logistic wins)',
      'Strict extrapolation requirements outside training range bounds',
    ],
    historicalMilestones: {
      year: 2001,
      creator: 'Leo Breiman',
      breakthrough: 'Combined bagging with random feature selection to decorrelate trees',
    },
  },

  {
    id: 'gradient-boosting',
    name: 'Gradient Boosting (GBDT)',
    speciesCode: 'SP-GB-012',
    family: 'Tree-Based Species',
    generation: 'Gen-3 (1999 Jerome Friedman)',
    algorithmType: 'Sequential Ensemble Boosting',
    architecture: 'Sequential Chain of Residual-Correcting Decision Trees',
    learningParadigm: 'Supervised Learning',
    inputType: 'Tabular Datasets',
    outputType: 'Accumulated Logits / Weighted Sum F(x) = ∑ γ_m h_m(x)',
    parameters: 'Sequential Tree Boosters and Shrinkage Coefficients',
    hyperparameters: {
      learningRate: 0.1,
      nEstimators: 100,
      maxDepth: 3,
      subsample: 0.8,
    },
    trainingStyle: 'Sequential Additive Stage-Wise Modeling',
    optimizationStrategy: 'Gradient Descent in Function Space fitting negative pseudo-residuals r_{im} = -[∂L(y_i, f(x_i))/∂f(x_i)]',
    decisionMechanism: 'Weighted additive ensemble sum of weak learner predictions',
    complexity: {
      trainTime: 'O(N_trees · n · d · log n)',
      inferTime: 'O(N_trees · depth)',
      memory: 'O(N_trees · nodes)',
      scalability: 'Requires sequential iteration; parallelized via histogram binning',
    },
    traits: {
      bias: 15,
      variance: 20,
      generalization: 92,
      interpretability: 55,
      speed: 75,
      memoryEfficiency: 75,
      parallelization: 65,
      featureEngineeringDependency: 30,
      noiseTolerance: 75,
      trainingStability: 85,
    },
    ancestors: ['decision-tree', 'random-forest'],
    descendants: ['xgboost', 'lightgbm', 'catboost'],
    ecosystem: 'Competitive Kaggle & Tabular Benchmark King',
    strengths: [
      'Unmatched accuracy on structured tabular datasets',
      'Supports arbitrary differentiable loss functions (MSE, LogLoss, Huber, Poisson)',
      'Effective handling of non-linear interactions without feature transformation',
    ],
    weaknesses: [
      'Prone to overfitting if learning rate and tree depth are poorly tuned',
      'Sequential training renders naive GBDT slower than Random Forests',
      'Sensitive to hyperparameter tuning tuning grid bounds',
    ],
    failureConditions: [
      'High noise ratio without early stopping or shrinkage regularization',
      'Unstructured image/audio data without spatial convolutions',
    ],
    historicalMilestones: {
      year: 1999,
      creator: 'Jerome H. Friedman',
      breakthrough: 'Formulated boosting as functional gradient descent on loss functions',
    },
  },

  {
    id: 'xgboost',
    name: 'XGBoost (Extreme Gradient Boosting)',
    speciesCode: 'SP-XGB-013',
    family: 'Tree-Based Species',
    generation: 'Gen-4 (2014 Tianqi Chen)',
    algorithmType: 'Regularized Second-Order Gradient Boosting',
    architecture: 'Hardware-Optimized Tree Boosting with Exact / Approx Histogram Splits',
    learningParadigm: 'Supervised Learning',
    inputType: 'Structured Tabular & Sparse Matrix Data',
    outputType: 'Weighted Stage-Wise Sum',
    parameters: 'Tree Splits, Node Weights w_j = -G_j / (H_j + λ)',
    hyperparameters: {
      maxDepth: 6,
      learningRate: 0.05,
      nEstimators: 300,
      gamma: 0.1, // Minimum loss reduction to split
      regLambda: 1.0, // L2 regularization
      regAlpha: 0.0, // L1 regularization
      treeMethod: 'hist', // GPU / CPU Histogram binning
    },
    trainingStyle: 'Second-Order Taylor Expansion Stage-Wise Optimization',
    optimizationStrategy: 'Objective Obj = ∑ [g_i f(x_i) + 1/2 h_i f²(x_i)] + γT + 1/2 λ ∑ w_j²',
    decisionMechanism: 'Optimized histogram tree split traversal with built-in missing value routing',
    complexity: {
      trainTime: 'O(N_trees · n_bins · d)',
      inferTime: 'O(N_trees · depth)',
      memory: 'O(n_bins · d + N_trees · nodes)',
      scalability: 'Massive GPU/CPU multi-threading and distributed cluster scale',
    },
    traits: {
      bias: 10,
      variance: 15,
      generalization: 96,
      interpretability: 50,
      speed: 92,
      memoryEfficiency: 88,
      parallelization: 95,
      featureEngineeringDependency: 25,
      noiseTolerance: 88,
      trainingStability: 94,
    },
    ancestors: ['gradient-boosting'],
    descendants: ['lightgbm', 'catboost'],
    ecosystem: 'Production ML, Kaggle Grandmaster Standard, Financial Risk',
    strengths: [
      'Second-order Taylor expansion provides rapid loss landscape convergence',
      'Built-in L1/L2 regularization prevents tree leaf weight overfitting',
      'Automatic handling of missing values with optimal branch direction learning',
    ],
    weaknesses: [
      'High memory consumption during exact greedy split search on huge datasets',
      'Numerous hyperparameters require systematic Bayesian optimization',
      'Not suited for streaming online learning updates',
    ],
    failureConditions: [
      'Unnormalized sparse text data with extremely high cardinality IDs',
    ],
    historicalMilestones: {
      year: 2014,
      creator: 'Tianqi Chen & Carlos Guestrin',
      breakthrough: 'Introduced second-order Taylor boosting with hardware-aware caching',
    },
  },

  {
    id: 'lightgbm',
    name: 'LightGBM',
    speciesCode: 'SP-LGB-014',
    family: 'Tree-Based Species',
    generation: 'Gen-4 (2017 Microsoft Research)',
    algorithmType: 'GOSS & EFB Histogram Boosting',
    architecture: 'Leaf-Wise (Best-First) Tree Growth with Gradient-Based One-Side Sampling',
    learningParadigm: 'Supervised Learning',
    inputType: 'Large-Scale Tabular Datasets',
    outputType: 'Leaf-Weighted Additive Prediction',
    parameters: 'Leaf-Wise Tree Nodes & Feature Bins',
    hyperparameters: {
      numLeaves: 31,
      learningRate: 0.05,
      nEstimators: 500,
      maxDepth: -1,
      minChildSamples: 20,
      featureFraction: 0.8,
    },
    trainingStyle: 'Gradient-Based One-Side Sampling (GOSS) & Exclusive Feature Bundling (EFB)',
    optimizationStrategy: 'Retains data instances with large gradients while randomly sampling instances with small gradients',
    decisionMechanism: 'Leaf-wise greedy growth choosing the leaf with maximum delta loss reduction',
    complexity: {
      trainTime: 'O(n_sample_goss · n_bins · d_efb)',
      inferTime: 'O(N_trees · numLeaves)',
      memory: 'O(n_bins · d)',
      scalability: '10x faster training & lower memory than traditional GBDT',
    },
    traits: {
      bias: 8,
      variance: 18,
      generalization: 95,
      interpretability: 48,
      speed: 99, // Super fast!
      memoryEfficiency: 96,
      parallelization: 96,
      featureEngineeringDependency: 20,
      noiseTolerance: 85,
      trainingStability: 90,
    },
    ancestors: ['xgboost'],
    descendants: ['catboost'],
    ecosystem: 'Big Data Tabular Systems & Real-Time Ad Tech',
    strengths: [
      'GOSS speeds up training by 10x by prioritizing high-gradient samples',
      'Exclusive Feature Bundling reduces sparse feature dimensions without loss',
      'Native handling of categorical features without One-Hot expansion',
    ],
    weaknesses: [
      'Leaf-wise growth can overfit easily on small datasets (n < 10,000)',
      'Requires careful tuning of num_leaves vs max_depth',
    ],
    failureConditions: [
      'Small datasets without setting min_child_samples constraint',
    ],
    historicalMilestones: {
      year: 2017,
      creator: 'Microsoft Research (Guolin Ke et al.)',
      breakthrough: 'Pioneered GOSS and EFB for orders of magnitude speedups',
    },
  },

  // --- NEURAL NETWORK & DEEP LEARNING LINEAGE ---
  {
    id: 'perceptron',
    name: 'Rosenblatt Perceptron',
    speciesCode: 'SP-NN-020',
    family: 'Neural Species',
    generation: 'Gen-1 (1958 Frank Rosenblatt)',
    algorithmType: 'Single-Layer Linear Threshold Unit',
    architecture: 'Single Neuron Input-to-Output wᵀx + b',
    learningParadigm: 'Supervised Learning',
    inputType: 'Vector Inputs x ∈ ℝᵈ',
    outputType: 'Binary Threshold Output y ∈ {-1, +1}',
    parameters: 'Weight vector w ∈ ℝᵈ, Bias b ∈ ℝ',
    hyperparameters: {
      learningRate: 0.01,
      maxEpochs: 1000,
    },
    trainingStyle: 'Online Perceptron Learning Rule',
    optimizationStrategy: 'Error-driven weight update w ← w + η(y_i - ŷ_i)x_i for misclassified samples',
    decisionMechanism: 'Step activation function f(z) = +1 if z ≥ 0 else -1',
    complexity: {
      trainTime: 'O(n · d · epochs)',
      inferTime: 'O(d)',
      memory: 'O(d)',
      scalability: 'Fast linear solver',
    },
    traits: {
      bias: 90,
      variance: 10,
      generalization: 60,
      interpretability: 90,
      speed: 99,
      memoryEfficiency: 99,
      parallelization: 70,
      featureEngineeringDependency: 90,
      noiseTolerance: 30,
      trainingStability: 80,
    },
    ancestors: ['linear-regression'],
    descendants: ['mlp', 'cnn', 'rnn'],
    ecosystem: 'Historical Foundation of Artificial Neural Networks',
    strengths: [
      'Historic proof that machine intelligence could learn from data',
      'Simple online update rule requiring zero derivative matrix computations',
    ],
    weaknesses: [
      'Failed on non-linearly separable problems (The famous XOR Crisis of 1969)',
      'No loss gradient magnitude — stops learning as soon as data is separated',
    ],
    failureConditions: [
      'Non-linear decision boundaries (Minsky & Papert 1969 proof)',
    ],
    historicalMilestones: {
      year: 1958,
      creator: 'Frank Rosenblatt',
      breakthrough: 'Constructed the Mark I Perceptron hardware machine at Cornell',
    },
  },

  {
    id: 'mlp',
    name: 'Multi-Layer Perceptron (MLP)',
    speciesCode: 'SP-NN-021',
    family: 'Neural Species',
    generation: 'Gen-2 (1986 Rumelhart, Hinton, Williams)',
    algorithmType: 'Deep Feedforward Neural Network (FNN)',
    architecture: 'Input Layer → Hidden Dense Layers with Non-Linear Activations → Output Layer',
    learningParadigm: 'Supervised / Self-Supervised',
    inputType: 'Dense Vector Embeddings & Tabular Features',
    outputType: 'Classification Logits or Continuous Values',
    parameters: 'Weight Matrices W⁽ˡ⁾ ∈ ℝ^{d_l × d_{l-1}}, Biases b⁽ˡ⁾',
    hyperparameters: {
      hiddenLayers: [128, 64, 32],
      activation: 'ReLU / GELU / Tanh',
      optimizer: 'AdamW / SGD with Momentum',
      learningRate: 0.001,
      dropout: 0.2,
      batchSize: 64,
    },
    trainingStyle: 'Backpropagation via Chain Rule Gradient Descent',
    optimizationStrategy: 'Minimizing Loss L(y, f(x; θ)) using ∂L/∂W⁽ˡ⁾ = ∂L/∂a⁽ˡ⁾ · ∂a⁽ˡ⁾/∂z⁽ˡ⁾ · ∂z⁽ˡ⁾/∂W⁽ˡ⁾',
    decisionMechanism: 'Non-linear composition of affine transformations f(x) = σ(W₃ σ(W₂ σ(W₁ x + b₁) + b₂) + b₃)',
    complexity: {
      trainTime: 'O(epochs · n · ∑ d_l · d_{l-1})',
      inferTime: 'O(∑ d_l · d_{l-1})',
      memory: 'O(∑ d_l · d_{l-1})',
      scalability: 'Universal Approximator; requires GPU hardware acceleration for deep topologies',
    },
    traits: {
      bias: 15,
      variance: 35,
      generalization: 85,
      interpretability: 25, // Black box!
      speed: 80,
      memoryEfficiency: 75,
      parallelization: 92, // GPU Tensor Parallel
      featureEngineeringDependency: 30,
      noiseTolerance: 80,
      trainingStability: 75,
    },
    ancestors: ['perceptron', 'logistic-regression'],
    descendants: ['cnn', 'rnn', 'transformer'],
    ecosystem: 'Deep Learning Foundation & Dense Representation Learning',
    strengths: [
      'Universal Approximation Theorem: Can approximate any continuous function',
      'Learns hierarchical non-linear feature representations automatically',
      'Highly parallelizable on Modern GPU/TPU Tensor Cores',
    ],
    weaknesses: [
      'Black-box model — difficult to interpret internal neuron activations',
      'Prone to Vanishing/Exploding Gradient problems in deep architectures',
      'Lacks spatial translation invariance (handled by CNNs) and sequence memory (handled by RNNs)',
    ],
    failureConditions: [
      'Vanishing gradients when using Deep Sigmoid/Tanh activations without Normalization',
      'Unstructured 2D image grids without spatial parameter sharing',
    ],
    historicalMilestones: {
      year: 1986,
      creator: 'David Rumelhart, Geoffrey Hinton, & Ronald Williams',
      breakthrough: 'Popularized the Backpropagation algorithm for training multi-layer networks',
    },
  },

  {
    id: 'cnn',
    name: 'Convolutional Neural Network (CNN / LeNet / AlexNet)',
    speciesCode: 'SP-NN-022',
    family: 'Neural Species',
    generation: 'Gen-3 (1989 LeCun / 2012 Krizhevsky)',
    algorithmType: 'Spatial Feature Hierarchy Convolutions',
    architecture: 'Conv2D Layers + Activation + MaxPool2D + Dense FC Layers',
    learningParadigm: 'Supervised Computer Vision',
    inputType: 'Spatial 2D/3D Tensor Image Arrays (H × W × C)',
    outputType: 'Class Probabilities / Bounding Box Coordinates',
    parameters: 'Kernel Filters (k_h × k_w × C_in × C_out) and Biases',
    hyperparameters: {
      kernelSize: 3,
      stride: 1,
      padding: 1,
      channels: [32, 64, 128],
      pooling: '2x2 Max Pooling',
    },
    trainingStyle: 'Spatial Filter Weight-Sharing Backpropagation',
    optimizationStrategy: 'Cross-Entropy Loss with Momentum SGD / Adam over 2D Cross-Correlation',
    decisionMechanism: 'Translational invariant local receptive field feature extraction (Edges → Textures → Shapes → Objects)',
    complexity: {
      trainTime: 'O(epochs · n · ∑ H · W · k² · C_in · C_out)',
      inferTime: 'O(∑ H · W · k² · C_in · C_out)',
      memory: 'O(C_out · H · W)',
      scalability: 'Massively scalable on GPUs; spatial weight sharing reduces parameters by 99% vs MLP',
    },
    traits: {
      bias: 12,
      variance: 30,
      generalization: 94,
      interpretability: 35, // Grad-CAM heatmaps
      speed: 88,
      memoryEfficiency: 82,
      parallelization: 99,
      featureEngineeringDependency: 5, // Zero manual vision features needed!
      noiseTolerance: 88,
      trainingStability: 85,
    },
    ancestors: ['mlp'],
    descendants: ['resnet', 'efficientnet', 'vit'],
    ecosystem: 'Computer Vision, Medical Imaging (MRI/CT), Autonomous Driving',
    strengths: [
      'Translational Invariance: Recognizes objects regardless of spatial location in frame',
      'Weight Sharing drastically reduces parameter count compared to fully connected layers',
      'Hierarchical feature learning from low-level edges to high-level semantic concepts',
    ],
    weaknesses: [
      'Lacks global context attention across distant pixels (addressed by Vision Transformers)',
      'Requires substantial labeled image data for deep feature learning',
      'Sensitive to adversarial pixel perturbations',
    ],
    failureConditions: [
      'Spatial rotation / scaling beyond augmentation ranges',
    ],
    historicalMilestones: {
      year: 2012,
      creator: 'Alex Krizhevsky, Ilya Sutskever, & Geoffrey Hinton',
      breakthrough: 'AlexNet won ImageNet 2012 by a landslide, igniting the modern Deep Learning revolution',
    },
  },

  {
    id: 'resnet',
    name: 'Residual Network (ResNet)',
    speciesCode: 'SP-NN-023',
    family: 'Neural Species',
    generation: 'Gen-4 (2015 Kaiming He et al.)',
    algorithmType: 'Deep Residual Learning with Skip Connections',
    architecture: 'Residual Blocks with Identity Skip Shortcuts F(x) + x',
    learningParadigm: 'Supervised / Self-Supervised Vision',
    inputType: 'High-Resolution Images & Feature Maps',
    outputType: 'Multi-Class Predictions / Embeddings',
    parameters: '11M (ResNet-18) to 60M (ResNet-152) Conv Weights',
    hyperparameters: {
      depth: 50, // ResNet-50
      blockType: 'Bottleneck (1x1, 3x3, 1x1)',
      baseChannels: 64,
      norm: 'Batch Normalization',
    },
    trainingStyle: 'Residual Mapping Optimization H(x) = F(x) + x',
    optimizationStrategy: 'Direct gradient highway allowing gradient flow through identity skip connections without decay',
    decisionMechanism: 'Sequential residual refinement of identity representations',
    complexity: {
      trainTime: 'O(depth · H · W · C²)',
      inferTime: 'O(3.8 GFLOPs for ResNet-50)',
      memory: 'O(depth · C · H · W)',
      scalability: 'Allowed scaling networks from 20 layers up to 1000+ layers deep',
    },
    traits: {
      bias: 5,
      variance: 20,
      generalization: 97,
      interpretability: 30,
      speed: 85,
      memoryEfficiency: 80,
      parallelization: 98,
      featureEngineeringDependency: 5,
      noiseTolerance: 90,
      trainingStability: 96,
    },
    ancestors: ['cnn'],
    descendants: ['efficientnet', 'vit'],
    ecosystem: 'Standard Backbone for Computer Vision, Medical MRI, & Object Detection',
    strengths: [
      'Solved the Degradation Problem: Deep networks no longer suffer higher training error than shallow ones',
      'Skip connections create smooth gradient highways preventing vanishing gradients',
      'Versatile backbone for detection (Faster R-CNN) and segmentation (U-Net)',
    ],
    weaknesses: [
      'High computational FLOP requirements for real-time mobile edge deployment',
    ],
    failureConditions: [
      'Severe memory constraints without quantization or channel pruning',
    ],
    historicalMilestones: {
      year: 2015,
      creator: 'Kaiming He, Xiangyu Zhang, Shaoqing Ren, & Jian Sun (MSRA)',
      breakthrough: 'Won ImageNet 2015 with 152 layers using Residual Skip Connections',
    },
  },

  // --- SEQUENTIAL & ATTENTION / TRANSFORMER LINEAGE ---
  {
    id: 'lstm',
    name: 'Long Short-Term Memory (LSTM)',
    speciesCode: 'SP-SEQ-030',
    family: 'Sequential Species',
    generation: 'Gen-3 (1997 Hochreiter & Schmidhuber)',
    algorithmType: 'Gated Recurrent Neural Network (RNN)',
    architecture: 'Recurrent Cell with Forget, Input, and Output Gates + Cell Memory State C_t',
    learningParadigm: 'Supervised Sequential Learning',
    inputType: 'Sequential Time Series / Text Embeddings (T × d)',
    outputType: 'Sequence of Hidden States h_t or Final Summary Vector',
    parameters: 'Gate Weight Matrices W_f, W_i, W_c, W_o ∈ ℝ^{h × (h+d)}',
    hyperparameters: {
      hiddenUnits: 256,
      numLayers: 2,
      bidirectional: true,
      dropout: 0.3,
    },
    trainingStyle: 'Backpropagation Through Time (BPTT)',
    optimizationStrategy: 'Gated cell state accumulation protecting gradient flow across long time steps',
    decisionMechanism: 'Additively update cell state C_t = f_t * C_{t-1} + i_t * C̃_t to retain long-term memories',
    complexity: {
      trainTime: 'O(T · n · h²)',
      inferTime: 'O(T · h²)',
      memory: 'O(T · h)',
      scalability: 'Sequential step-by-step nature prevents GPU parallelization along sequence length T',
    },
    traits: {
      bias: 20,
      variance: 30,
      generalization: 86,
      interpretability: 20,
      speed: 55, // Slow due to sequential loop!
      memoryEfficiency: 70,
      parallelization: 25, // Poor T-axis parallelization
      featureEngineeringDependency: 25,
      noiseTolerance: 82,
      trainingStability: 80,
    },
    ancestors: ['mlp', 'perceptron'],
    descendants: ['attention', 'transformer'],
    ecosystem: 'Time Series Forecasting, Speech Recognition, Early NLP Translation',
    strengths: [
      'Overcame the Vanishing Gradient problem of classic Vanilla RNNs using additive cell state gating',
      'Maintains long-range temporal context across hundreds of sequence steps',
    ],
    weaknesses: [
      'Sequential O(T) recurrence cannot be parallelized across sequence length on GPUs',
      'Struggles with extremely long sequences (T > 1000) due to memory bottleneck',
    ],
    failureConditions: [
      'Extremely long contexts (T > 1000 steps) leading to information bottleneck',
    ],
    historicalMilestones: {
      year: 1997,
      creator: 'Sepp Hochreiter & Jürgen Schmidhuber',
      breakthrough: 'Invented gated memory cells to solve vanishing gradient in recurrent networks',
    },
  },

  {
    id: 'transformer',
    name: 'Transformer (Attention Is All You Need)',
    speciesCode: 'SP-ATT-040',
    family: 'Attention & LLM Species',
    generation: 'Gen-5 (2017 Vaswani et al.)',
    algorithmType: 'Multi-Head Self-Attention Architecture',
    architecture: 'Encoder-Decoder Stack with Multi-Head Self-Attention & Feedforward Blocks',
    learningParadigm: 'Self-Supervised Pre-Training + Task Fine-Tuning',
    inputType: 'Token Embeddings with Positional Encodings (B × T × d_model)',
    outputType: 'Target Token Probabilities / Hidden States',
    parameters: 'Query, Key, Value Projections (W_Q, W_K, W_V) and Feedforward Weights',
    hyperparameters: {
      dModel: 768,
      numHeads: 12,
      numLayers: 12,
      dFF: 3072,
      maxSeqLen: 2048,
    },
    trainingStyle: 'Masked / Causal Language Modeling Pre-Training',
    optimizationStrategy: 'Scaled Dot-Product Attention Attention(Q,K,V) = softmax(QKᵀ / √d_k) V with AdamW Optimizer',
    decisionMechanism: 'Computes dense dynamic pairwise affinity weights between all tokens in O(1) step distance',
    complexity: {
      trainTime: 'O(T² · d_model + T · d_model²)',
      inferTime: 'O(T² · d_model) — reduced via KV Caching to O(T · d_model)',
      memory: 'O(T² · numHeads)',
      scalability: 'Massively parallelizable on GPU/TPU clusters across sequence dimension T',
    },
    traits: {
      bias: 5,
      variance: 15,
      generalization: 99,
      interpretability: 25,
      speed: 90, // Highly parallel training!
      memoryEfficiency: 60, // O(T²) attention matrix memory
      parallelization: 99,
      featureEngineeringDependency: 0, // Learns tokens & context end-to-end!
      noiseTolerance: 94,
      trainingStability: 90,
    },
    ancestors: ['lstm', 'mlp'],
    descendants: ['bert', 'gpt'],
    ecosystem: 'Modern Foundation AI, Large Language Models, Multi-Modal Vision-Language',
    strengths: [
      'Complete parallelization during training — no sequential recurrent loops!',
      'O(1) direct path length between any two tokens in sequence prevents context decay',
      'Scales predictably with compute & data according to Neural Scaling Laws',
    ],
    weaknesses: [
      'Quadratic O(T²) memory and compute complexity with sequence length T',
      'Requires massive datasets and high compute for self-supervised pre-training',
      'Lacks inherent inductive bias — relies entirely on data to learn position & hierarchy',
    ],
    failureConditions: [
      'Unconstrained context length without flash attention / KV caching causing OOM',
    ],
    historicalMilestones: {
      year: 2017,
      creator: 'Ashish Vaswani et al. (Google Brain / Google Research)',
      breakthrough: 'Published "Attention Is All You Need", replacing recurrence with self-attention',
    },
  },

  {
    id: 'gpt',
    name: 'GPT (Generative Pre-trained Transformer / GPT-4)',
    speciesCode: 'SP-LLM-041',
    family: 'Attention & LLM Species',
    generation: 'Gen-6 (2018–2024 OpenAI)',
    algorithmType: 'Autoregressive Decoder-Only Transformer',
    architecture: 'Stacked Causal Masked Multi-Head Self-Attention Decoders',
    learningParadigm: 'Self-Supervised Next-Token Prediction + RLHF Alignment',
    inputType: 'Text Prompts / Multi-Modal Tokens',
    outputType: 'Autoregressive Generated Token Stream P(w_t | w_1, ..., w_{t-1})',
    parameters: '117M (GPT-1) to 1.8 Trillion (GPT-4 Mixture-of-Experts)',
    hyperparameters: {
      contextWindow: 128000,
      temperature: 0.7,
      topP: 0.9,
      presencePenalty: 0.0,
    },
    trainingStyle: 'Causal Language Modeling (CLM) + Instruct RLHF / DPO Alignment',
    optimizationStrategy: 'Cross-Entropy Loss on Next-Token Prediction with Rotary Position Embeddings (RoPE)',
    decisionMechanism: 'Causal triangular masked self-attention predicting probabilities over a 100k+ vocabulary',
    complexity: {
      trainTime: 'ExaFLOPs over months of 25,000+ GPU cluster runs',
      inferTime: 'O(T) per token with KV-Cache',
      memory: 'Hundreds of GBs VRAM (Quantized via AWQ / GGUF)',
      scalability: 'Emergent reasoning abilities with scale (In-context learning, code, math)',
    },
    traits: {
      bias: 2,
      variance: 10,
      generalization: 99,
      interpretability: 15,
      speed: 75,
      memoryEfficiency: 50,
      parallelization: 98,
      featureEngineeringDependency: 0,
      noiseTolerance: 96,
      trainingStability: 92,
    },
    ancestors: ['transformer'],
    descendants: [],
    ecosystem: 'Generative AI, Autonomous AI Agents, Conversational Assistants, Code Generation',
    strengths: [
      'Unmatched general reasoning, code generation, and multi-domain problem solving',
      'Zero-shot and few-shot in-context learning without updating model weights',
      'Supports vast multi-modal contexts (text, vision, audio, code)',
    ],
    weaknesses: [
      'Hallucinations — generates plausible-sounding incorrect statements',
      'High inference latency and heavy GPU VRAM memory requirements',
      'Static knowledge cutoff date unless augmented with RAG / Web Search',
    ],
    failureConditions: [
      'Complex multi-step arithmetic / logical deduction without chain-of-thought prompting',
    ],
    historicalMilestones: {
      year: 2018,
      creator: 'OpenAI (Alec Radford, Ilya Sutskever et al.)',
      breakthrough: 'Demonstrated scaling decoder transformers leads to emergent general intelligence',
    },
  },
]
